version: '1.0.{build}'

image: Visual Studio 2017

install:
  - ps: Install-Module InvokeBuild
  - ps: Install-Module Pester
  - ps: Install-Module SqlServer -AllowClobber
  - choco install -y docker
  - choco install -y docker-machine
  - docker version

platform:
  - x64

build_script:
  - ps: Invoke-Build Build

test_script:
  - ps: .\Test\appveyor.Pester.ps1