version: '1.0.{build}'

image: Visual Studio 2017

install:
  - ps: Install-Module InvokeBuild -Force
  - ps: Install-Module Pester -Force -SkipPublisherCheck
  - ps: Install-Module SqlServer -AllowClobber -Force
  - ps: Install-Module PSDocker
  - docker version

platform:
  - x64

build_script:
  - ps: Invoke-Build Build

test_script:
  - ps: .\Test\appveyor.Pester.ps1